version: '3.8'

services:
  frontend:
    image: sudhansu063/raktkosh:frontend
    ports:
      - "5173:5173"

  backend:
    image: sudhansu063/raktkosh:backend
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - frontend
